### ISSUE TITLE
Bashism in string comparison breaks the consul service

### ISSUE THREAD

**Issue by rallyemax** [servian/hashiqube#12]
The shell executing the quoted commands is Dash, and the string comparison `[ $i == systemd-tmpfiles-setup.service ]` is not POSIX-compliant, causing that loop to throw several errors and the deletion of files _other than_ `systemd-tmpfiles-setup.service` to fail. Dash is very particular about POSIX.

Not sure whether it's this or something else that makes the consul service fail (there are many errors in the output and I'm still chasing them down), but at least this one is an easy fix: `[ "$i" = "systemd-tmpfiles-setup.service" ]`

What's _not_ an easy fix is checking all the other shell code for similar mistakes.

https://github.com/servian/hashiqube/blob/3c20abbc9643d986d9ce8ff35783b1ea23ddd0ec/Dockerfile#L23-L30

Edit: The deletion is of files other than the matched string, obviously, but I forgot to invert the English logic...

**Comment by star3am** [comment]
@rallyemax thanks for opening this issue, I will take a look.

**Comment by rallyemax** [comment]
On closer examination, the script error didn't quite do what I expected it to. The `test` command (in this case invoked with `[`) causes errors due to the incorrect conditional, and thus it always evaluates false-y. That means that *all* files in `/lib/systemd/system/sysinit.target.wants/` are deleted.

Fixing this bug causes all files _except_ `systemd-tmpfiles-setup.service` to be deleted.

But this uncovers *another* bug, because `systemd-tmpfiles-setup.service` creates the file `/run/nologin`, which is used by [pam_nologin](https://linux.die.net/man/8/pam_nologin) to prevent SSH logins by unprivileged users.

Normally the `nologin` file is deleted by `systemd-user-sessions.service`, but this service is normally dependent on the `multi-user` target...and in this case we've wiped all such dependencies:
```
rm -f /lib/systemd/system/multi-user.target.wants/*
```
Masked bugs aren't fun.

What's the correct solution? Is there a reason for preventing `systemd-user-sessions.service` from running? If so, the easy fix to the immediate issue is to just delete `/run/nologin`.

If not, we can exempt the `systemd-user-sessions.service` symlink from deletion.

But what other effects will that service have?

Thanks for taking a look.

----

For reference, here is a narrative bug report on the PAM/ssh issue:

Fixing the faulty conditional seems to have broken SSH inside the container. I tried to bring the system up and after "rebooting" the consul container, the script's attempt to establish an SSH connection to the box failed:
```
hashiqube0.service.consul: Warning: Remote connection disconnect. Retrying...
hashiqube0.service.consul: Warning: Remote connection disconnect. Retrying...
[repeated several times, then timed out]
```
I opened a shell into the container and the logs indicated that PAM was blocking the connection attempt, but the log messages weren't terribly helpful:
```
hashiqube0.service.consul sshd[2609]: fatal: Access denied for user vagrant by PAM account configuration [preauth]
```
I tried to SSH in myself (finding the key was not obvious: the public key appears hardcoded in various scripts, other scripts download it from a statically-defined githubusercontent URL; and the private key is installed on the host system as part of the `vagrant` package...messy) and got a useful message:
```
System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8).
```
Following that lead, it turns out that `systemd-tmpfiles-setup.service` creates `/run/nologin`, which is one of the locations for [pam_nologin](https://linux.die.net/man/8/pam_nologin). This file normally gets deleted by `systemd-user-sessions.service`.

However, `systemd-user-sessions.service` is normally wanted by the `multi-user` systemd target...and in the Dockerfile quoted in full in the original issue, we have:
```
rm -f /lib/systemd/system/multi-user.target.wants/*
```
This means `/run/nologin` remains and prevents the vagrant user from SSH-ing into the machine.

The solution is to either delete the file manually or to leave `systemd-user-sessions.service` in `/lib/systemd/system/multi-user.target.wants/`.

**Comment by star3am** [comment]
@rallyemax I am sorry I cannot replicate this, I have tried on Windows, Linux, Mac Intel and ARM, the container boots fine, and I can do vagrant ssh and login fine. Closing for now,

**Comment by noisycomputation** [comment]
Have you checked your logs? The attempt to *not* remove `systemd-tmpfiles-setup.service` fails inside the docker container's Ubuntu runtime because it's incorrect POSIX code running inside of Dash, which is rather intolerant of such things. Because this is happening inside the container, the outer host is irrelevant.

If it's OK to wipe `systemd-tmpfiles-setup.service` then just remove the exception and expressly wipe everything in `/lib/systemd/system/sysinit.target.wants/`.

The real bug is masked. If you fix the outer bug and delete everything in `/lib/systemd/system/sysinit.target.wants/` but leave `systemd-tmpfiles-setup.service` in place, then the stack will not come up, because the primary container will be unreachable for the `vagrant` user via SSH due to a PAM lockout.

In a normal boot, `systemd-tmpfiles-setup.service` [creates](https://github.com/systemd/systemd/blob/3efadceb9ef5073dece41d1e6044ca0176732417/tmpfiles.d/systemd-nologin.conf#L11) `/run/nologin`, which prevents non-root users from logging into the system, and `systemd-user-sessions.service` [removes](https://github.com/systemd/systemd/blob/3efadceb9ef5073dece41d1e6044ca0176732417/src/user-sessions/user-sessions.c#L33) it.

Not fixing this will leave one obvious but perhaps innocuous bug and one masked but fatal bug in place. Some day someone will fix the outer bug and run smack into the second bug. The second bug is quite a bit more subtle than the first. I suppose this issue thread will exist, but why not fix it?

This is the minimal but not recommended fix, which accomplishes the intent of the original code using the original style:
```
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ "$i" = "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \ 
    (cd /lib/systemd/system/multi-user.target.wants/; for i in *; do [ "$i" = "systemd-user-sessions.service" ] || rm -f $i; done); \
    rm -f /etc/systemd/system/*.wants/*; \ 
    [...]
```
I recommend changing this pattern to make it more readable, more direct, and extensible to multiple exceptions if the need arises:
```
RUN find /lib/systemd/system/sysinit.target.wants -mindepth 1 -not -name "systemd-tmpfiles-setup.service" -delete; \
    find /lib/systemd/system/multi-user.target.wants -mindepth 1 -not -name "systemd-user-sessions.service" -delete; \
    rm -f /etc/systemd/system/*.wants/*; \
    [...]
```
Now, if there is a reason to run `systemd-tmpfiles-setup.service` but not `systemd-user-sessions.service`, then the `/run/nologin` file can be manually deleted inside the container on every startup. I don't see any other things that `tmpfiles-setup` does and `user-sessions` undoes, so this should be OK at the moment, but it would require a systemd service with the appropriate dependencies (so that it runs after `/run/nologin` is created).

**Comment by star3am** [comment]
@noisycomputation thank you for your valuable feedback, I appreciate it, I now better understand what you mean, thank you for going in depth into the problem. 

I have tested this change and it works, and I am able to login
```
diff --git a/Dockerfile b/Dockerfile
index 1ae1859f..569bc781 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -20,8 +20,8 @@ RUN apt-get update && \
     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 # Enable systemd (from Matthew Warman's mcwarman/vagrant-provider)
-RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
-    rm -f /lib/systemd/system/multi-user.target.wants/*; \
+RUN find /lib/systemd/system/sysinit.target.wants -mindepth 1 -not -name "systemd-tmpfiles-setup.service" -delete; \
+    find /lib/systemd/system/multi-user.target.wants -mindepth 1 -not -name "systemd-user-sessions.service" -delete; \
```

did I miss anything?

**Comment by rallyemax** [comment]
That looks good, thanks for taking a deeper look.

**Comment by star3am** [comment]
> That looks good, thanks for taking a deeper look.

@rallyemax my pleasure and thanks for raising it, I have pushed it already, closing this issue, let me know if you need anything else
